#!/bin/bash
#
# Configuration Manager - Unified Configuration System
#
# This script manages the unified configuration system that eliminates
# redundant configuration parameters across multiple files.
#
# Usage:
#   ./config_manager.sh generate    # Generate all config files from master
#   ./config_manager.sh validate    # Validate master configuration
#   ./config_manager.sh sync       # Sync changes to all config files
#   ./config_manager.sh clean      # Remove generated config files
#

set -euo pipefail

# Script directory and paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_DIR="$PROJECT_ROOT/config"

# Master configuration file
MASTER_CONFIG="$CONFIG_DIR/deployment.conf"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Load master configuration
load_master_config() {
    if [[ ! -f "$MASTER_CONFIG" ]]; then
        log_error "Master configuration file not found: $MASTER_CONFIG"
        exit 1
    fi
    
    log_info "Loading master configuration: $MASTER_CONFIG"
    
    # Source the configuration file safely
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        [[ $key =~ ^[[:space:]]*# ]] && continue
        [[ -z $key ]] && continue
        
        # Remove quotes, comments, and whitespace
        key=$(echo "$key" | tr -d ' ')
        value=$(echo "$value" | sed 's/[[:space:]]*#.*//' | sed 's/^["'"'"']\|["'"'"']$//g' | xargs)
        
        # Export the variable
        export "$key"="$value"
    done < "$MASTER_CONFIG"
    
    log_success "Master configuration loaded successfully"
}

# Generate bootstrap configuration
generate_bootstrap_config() {
    local output_file="$PROJECT_ROOT/bootstrap.conf"
    
    log_info "Generating bootstrap configuration: $output_file"
    
    cat > "$output_file" << EOF
# Arch Linux Hyprland Desktop Automation Configuration
# This file is automatically generated from config/deployment.conf
# DO NOT EDIT MANUALLY - Changes will be overwritten

# Repository Settings
REPO_URL=${REPO_URL}
BRANCH=${BRANCH}

# System Configuration
HOSTNAME=${HOSTNAME}
USERNAME=${USERNAME}
TIMEZONE=${TIMEZONE}
LOCALE=${LOCALE}
KEYMAP=${KEYMAP}

# Deployment Profile (work, personal, development)
PROFILE=${DEPLOYMENT_PROFILE}

# Security Settings
ENABLE_ENCRYPTION=${DISK_ENCRYPTION}

# Automation Settings
AUTO_REBOOT=${AUTO_REBOOT}

# Password Management
USER_PASSWORD=${USER_PASSWORD}
ROOT_PASSWORD=${ROOT_PASSWORD}
ENCRYPTION_PASSPHRASE=${ENCRYPTION_PASSPHRASE}

# Network Configuration
WIFI_SSID=${WIFI_SSID}
WIFI_PASSWORD=${WIFI_PASSWORD}

# Optional: Custom package lists
EXTRA_PACKAGES=${CUSTOM_PACKAGES}
AUR_PACKAGES=""

# VirtualBox Testing Options
VM_MEMORY=${VM_MEMORY}
VM_DISK_SIZE=${VM_DISK_SIZE}
VM_OPTIMIZATION=${VM_OPTIMIZATIONS}
EOF

    log_success "Bootstrap configuration generated"
}

# Generate deploy.sh configuration
generate_deploy_config() {
    local output_file="$CONFIG_DIR/deploy.conf"
    
    log_info "Generating deploy.sh configuration: $output_file"
    
    cat > "$output_file" << EOF
# Arch Linux Desktop Deployment Configuration
# This file is automatically generated from config/deployment.conf
# DO NOT EDIT MANUALLY - Changes will be overwritten

# User Configuration
USER_NAME="${USERNAME}"
PASSWORD_MODE="${PASSWORD_MODE}"
PASSWORD_FILE="${PASSWORD_FILE}"
PROFILE="${DEPLOYMENT_PROFILE}"

# System Configuration
HOSTNAME="${HOSTNAME}"
ENCRYPTION_ENABLED=${DISK_ENCRYPTION}
FILESYSTEM="${FILESYSTEM}"

# Network Configuration
NETWORK_MODE="${NETWORK_MODE}"
WIFI_SSID="${WIFI_SSID}"
WIFI_PASSWORD="${WIFI_PASSWORD}"

# Deployment Options
SKIP_VALIDATION=false
ENABLE_AUR=${ENABLE_AUR}
CUSTOM_PACKAGES="${CUSTOM_PACKAGES}"

# Logging and Debug
LOG_LEVEL=3
DEBUG=${DEBUG_MODE}

# Advanced Options
BOOTLOADER="${BOOTLOADER}"
TIMEZONE="${TIMEZONE}"
KEYMAP="${KEYMAP}"
LOCALE="${LOCALE}"
MIRROR_COUNTRY="${MIRROR_COUNTRY}"

# Security Configuration
ENABLE_FIREWALL=${ENABLE_FIREWALL}
ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
ENABLE_AUDIT=${ENABLE_AUDIT}
ENABLE_SSH=${ENABLE_SSH}
SSH_PORT=22
SSH_PERMIT_ROOT_LOGIN=false

# Desktop Environment Options
DESKTOP_SESSION="${DESKTOP_SESSION}"
DISPLAY_MANAGER="${DISPLAY_MANAGER}"
AUDIO_SYSTEM="${AUDIO_SYSTEM}"
ENABLE_GAMING=false
ENABLE_DEVELOPMENT=true

# Hardware Optimization
ENABLE_HARDWARE_ACCEL=${ENABLE_HARDWARE_ACCEL}

# Backup and Recovery
ENABLE_SNAPSHOTS=false

# Post-deployment Actions
AUTO_REBOOT=${AUTO_REBOOT}
AUTO_UPDATE=true
INSTALL_EXTRAS=false

# Error Handling
CONTINUE_ON_ERROR=${CONTINUE_ON_ERROR}
MAX_RETRIES=${MAX_RETRIES}
CLEANUP_ON_EXIT=${CLEANUP_ON_EXIT}

# Performance Tuning
PARALLEL_JOBS=${PARALLEL_JOBS}
DOWNLOAD_TIMEOUT=${DOWNLOAD_TIMEOUT}
NETWORK_TIMEOUT=${NETWORK_TIMEOUT}
DISK_TIMEOUT=${DISK_TIMEOUT}

# CI/CD Configuration
CI_MODE=${CI_MODE}
CI_NON_INTERACTIVE=${CI_NON_INTERACTIVE}
EOF

    log_success "Deploy configuration generated"
}

# Generate example deployment YAML
generate_example_deployment_yaml() {
    local output_file="$PROJECT_ROOT/example_deployment_config.yml"
    
    log_info "Generating example deployment YAML: $output_file"
    
    cat > "$output_file" << EOF
# Example Deployment Configuration
# This file is automatically generated from config/deployment.conf
# Copy this file to deployment_config.yml and customize for your setup

# System Configuration
system:
  hostname: "${HOSTNAME}"
  timezone: "${TIMEZONE}"
  locale: "${LOCALE}"
  keymap: "${KEYMAP}"

# User Configuration
user:
  username: "${USERNAME}"
  password: "${USER_PASSWORD}"
  shell: "/bin/zsh"

# Network Configuration
network:
  wifi:
    enabled: true
    ssid: "${WIFI_SSID}"
    password: "${WIFI_PASSWORD}"
    security: "wpa3"
  ethernet:
    enabled: true
    dhcp: true

# Disk Configuration
disk:
  device: "/dev/sda"
  encryption:
    enabled: ${DISK_ENCRYPTION}
    passphrase: "${ENCRYPTION_PASSPHRASE}"
  partitions:
    efi_size: "1G"
    swap_size: "8G"

# Desktop Configuration
desktop:
  environment: "${DESKTOP_SESSION}"
  display_manager: "${DISPLAY_MANAGER}"
  theme: "${DESKTOP_THEME}"
  auto_login: ${AUTO_LOGIN}

# Security Configuration
security:
  firewall:
    enabled: ${ENABLE_FIREWALL}
  fail2ban:
    enabled: ${ENABLE_FAIL2BAN}
  audit:
    enabled: ${ENABLE_AUDIT}
  ssh:
    password_auth: false
    root_login: false

# Automation Settings
automation:
  skip_confirmations: ${SKIP_CONFIRMATIONS}
  auto_reboot: ${AUTO_REBOOT}
  backup_configs: true
  log_level: "${LOG_LEVEL}"

# VirtualBox Testing
virtualbox:
  guest_additions: ${VM_GUEST_ADDITIONS}
  vm_optimizations: ${VM_OPTIMIZATIONS}

# Development Tools
development:
  git:
    username: "${GIT_USERNAME}"
    email: "${GIT_EMAIL}"
  ssh_keys:
    generate: ${GENERATE_SSH_KEYS}
    type: "${SSH_KEY_TYPE}"
EOF

    log_success "Example deployment YAML generated"
}

# Generate Ansible group variables
generate_ansible_group_vars() {
    local output_file="$PROJECT_ROOT/configs/ansible/group_vars/all/vars.yml"
    
    log_info "Generating Ansible group variables: $output_file"
    
    mkdir -p "$(dirname "$output_file")"
    
    cat > "$output_file" << EOF
---
# Global variables for all hosts
# This file is automatically generated from config/deployment.conf
# DO NOT EDIT MANUALLY - Changes will be overwritten

# System configuration
system:
  locale: "${LOCALE}"
  keymap: "${KEYMAP}"
  timezone: "${TIMEZONE}"
  hostname: "${HOSTNAME}"
  
# User configuration
users:
  main_user: "${USERNAME}"
  groups:
    - wheel
    - audio
    - video
    - storage
    - network
    - input
    - optical
  shell: /bin/zsh

# Package management
packages:
  base_packages:
    - base-devel
    - linux-firmware
    - networkmanager
    - sudo
    - openssh
    - git
    - reflector
    - neovim
    - tmux
    - htop
    - zsh
    - curl
    - wget
    - tree
    - zip
    - unzip
    - trash-cli
    
  aur_packages:
    - visual-studio-code-bin
    - discord
    - zoom
    - hyprpaper
    - bibata-cursor-theme
    
# Desktop environment
desktop:
  environment: ${DESKTOP_SESSION}
  display_manager: ${DISPLAY_MANAGER}
  
  hyprland_packages:
    - hyprland
    - waybar
    - wofi
    - mako
    - kitty
    - thunar
    - grim
    - slurp
    - wl-clipboard
    - xdg-desktop-portal-hyprland
    - polkit-gnome
    - qt5-wayland
    - qt6-wayland
    
  graphics_packages:
    - mesa
    - intel-media-driver
    - vulkan-intel
    
  audio_packages:
    - pipewire
    - pipewire-pulse
    - pipewire-alsa
    - wireplumber
    
  applications:
    - firefox
    - thunderbird
    - libreoffice-still
    - vlc
    - okular
    - cups
    
# Security configuration
security:
  firewall:
    enabled: ${ENABLE_FIREWALL}
    default_policy: deny
    
  fail2ban:
    enabled: ${ENABLE_FAIL2BAN}
    
  audit:
    enabled: ${ENABLE_AUDIT}
    
  ssh:
    port: 22
    permit_root_login: "no"
    password_authentication: "no"
    pubkey_authentication: "yes"
    
# Power management
power:
  tlp:
    enabled: true
    
  thermald:
    enabled: true
    
# Mirrors
mirrors:
  country: "${MIRROR_COUNTRY}"
  
# Bootloader
bootloader:
  type: ${BOOTLOADER}
  timeout: 5
  
# Logging
logging:
  directory: /var/log/ansible
  max_size: 100M
  backup_count: 5
EOF

    log_success "Ansible group variables generated"
}

# Generate profile-specific Ansible variables
generate_profile_ansible_vars() {
    local profile="${DEPLOYMENT_PROFILE}"
    local output_file="$PROJECT_ROOT/configs/profiles/${profile}/ansible/vars.yml"
    
    log_info "Generating profile Ansible variables: $output_file"
    
    mkdir -p "$(dirname "$output_file")"
    
    cat > "$output_file" << EOF
---
# ${profile^} Profile Configuration
# This file is automatically generated from config/deployment.conf
# DO NOT EDIT MANUALLY - Changes will be overwritten

profile_name: "${profile}"
profile_type: "${profile^^}"

# System Configuration
system:
  hostname: "${HOSTNAME}"
  timezone: "${TIMEZONE}"
  locale: "${LOCALE}"
  keymap: "${KEYMAP}"

# User Configuration
user:
  username: "${USERNAME}"
  shell: "/bin/bash"
  groups:
    - wheel
    - audio
    - video
    - network
    - storage

# Desktop Configuration
desktop:
  environment: "${DESKTOP_SESSION}"
  theme: "${DESKTOP_THEME}"
  auto_login: ${AUTO_LOGIN}

# Security Configuration
security:
  firewall:
    enabled: ${ENABLE_FIREWALL}
    default_policy: "deny"
  fail2ban:
    enabled: ${ENABLE_FAIL2BAN}
  audit:
    enabled: ${ENABLE_AUDIT}
  ssh:
    port: 22
    password_auth: false
    root_login: false
    key_types: ["${SSH_KEY_TYPE}"]

# Development Tools
development:
  git:
    username: "${GIT_USERNAME}"
    email: "${GIT_EMAIL}"
  ssh_keys:
    generate: ${GENERATE_SSH_KEYS}
    type: "${SSH_KEY_TYPE}"

# Automation Configuration
automation:
  skip_confirmations: ${SKIP_CONFIRMATIONS}
  auto_reboot: ${AUTO_REBOOT}
  backup_configs: true
  log_level: "${LOG_LEVEL}"
EOF

    log_success "Profile Ansible variables generated"
}

# Generate archinstall configuration
generate_archinstall_config() {
    local profile="${DEPLOYMENT_PROFILE}"
    local output_file="$PROJECT_ROOT/configs/profiles/${profile}/archinstall/user_configuration.json"
    
    log_info "Generating archinstall configuration: $output_file"
    
    mkdir -p "$(dirname "$output_file")"
    
    cat > "$output_file" << EOF
{
    "!users": [
        {
            "username": "${USERNAME}",
            "!password": null,
            "sudo": true
        }
    ],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "${AUDIO_SYSTEM}"
    },
    "bootloader": "systemd-bootctl",
    "config_version": "2.6.0",
    "debug": ${DEBUG_MODE},
    "disk_config": {
        "config_type": "manual_partitioning",
        "device_modifications": []
    },
    "hostname": "${HOSTNAME}",
    "kernels": [
        "linux",
        "linux-lts"
    ],
    "locale_config": {
        "kb_layout": "${KEYMAP}",
        "sys_enc": "UTF-8",
        "sys_lang": "$(echo ${LOCALE} | cut -d'.' -f1)"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Worldwide": [
                "https://mirror.rackspace.com/archlinux/\$repo/os/\$arch",
                "https://mirror.leaseweb.net/archlinux/\$repo/os/\$arch"
            ]
        }
    },
    "network_config": {
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "base-devel",
        "git",
        "openssh",
        "reflector",
        "networkmanager",
        "sudo",
        "neovim",
        "htop",
        "curl",
        "wget",
        "tmux",
        "fail2ban",
        "ufw",
        "audit"
    ],
    "parallel downloads": ${PARALLEL_DOWNLOADS},
    "profile_config": null,
    "script": "guided",
    "silent": false,
    "swap": ${ENABLE_SWAP},
    "timezone": "${TIMEZONE}",
    "version": "2.6.0"
}
EOF

    log_success "Archinstall configuration generated"
}

# Validate master configuration
validate_config() {
    log_info "Validating master configuration..."
    
    local errors=0
    
    # Check required fields
    local required_fields=(
        "HOSTNAME" "USERNAME" "TIMEZONE" "LOCALE" "KEYMAP" 
        "DEPLOYMENT_PROFILE" "DESKTOP_SESSION" "DISPLAY_MANAGER"
    )
    
    for field in "${required_fields[@]}"; do
        if [[ -z "${!field:-}" ]]; then
            log_error "Required field $field is empty or not set"
            ((errors++))
        fi
    done
    
    # Validate profile
    if [[ ! "${DEPLOYMENT_PROFILE}" =~ ^(work|personal|development)$ ]]; then
        log_error "Invalid DEPLOYMENT_PROFILE: ${DEPLOYMENT_PROFILE}. Must be: work, personal, or development"
        ((errors++))
    fi
    
    # Validate password mode
    if [[ ! "${PASSWORD_MODE}" =~ ^(env|file|generate|interactive)$ ]]; then
        log_error "Invalid PASSWORD_MODE: ${PASSWORD_MODE}. Must be: env, file, generate, or interactive"
        ((errors++))
    fi
    
    # Validate boolean values
    local boolean_fields=(
        "DISK_ENCRYPTION" "ENABLE_FIREWALL" "ENABLE_FAIL2BAN" "ENABLE_AUDIT"
        "ENABLE_SSH" "ENABLE_AUR" "AUTO_LOGIN" "AUTO_REBOOT"
    )
    
    for field in "${boolean_fields[@]}"; do
        if [[ ! "${!field:-}" =~ ^(true|false)$ ]]; then
            log_error "Invalid boolean value for $field: ${!field}. Must be: true or false"
            ((errors++))
        fi
    done
    
    if [[ $errors -eq 0 ]]; then
        log_success "Configuration validation passed"
        return 0
    else
        log_error "Configuration validation failed with $errors errors"
        return 1
    fi
}

# Generate all configuration files
generate_all_configs() {
    log_info "Generating all configuration files from master configuration..."
    
    load_master_config
    
    if ! validate_config; then
        log_error "Configuration validation failed. Aborting generation."
        exit 1
    fi
    
    # Generate all configuration files
    generate_bootstrap_config
    generate_deploy_config
    generate_example_deployment_yaml
    generate_ansible_group_vars
    generate_profile_ansible_vars
    generate_archinstall_config
    
    log_success "All configuration files generated successfully"
}

# Clean generated configuration files
clean_configs() {
    log_info "Cleaning generated configuration files..."
    
    local files_to_clean=(
        "$PROJECT_ROOT/bootstrap.conf"
        "$CONFIG_DIR/deploy.conf"
        "$PROJECT_ROOT/example_deployment_config.yml"
        "$PROJECT_ROOT/configs/ansible/group_vars/all/vars.yml"
        "$PROJECT_ROOT/configs/profiles/*/ansible/vars.yml"
        "$PROJECT_ROOT/configs/profiles/*/archinstall/user_configuration.json"
    )
    
    for file_pattern in "${files_to_clean[@]}"; do
        if [[ "$file_pattern" == *"*"* ]]; then
            # Handle glob patterns
            for file in $file_pattern; do
                if [[ -f "$file" ]]; then
                    rm "$file"
                    log_info "Removed: $file"
                fi
            done
        else
            # Handle exact file paths
            if [[ -f "$file_pattern" ]]; then
                rm "$file_pattern"
                log_info "Removed: $file_pattern"
            fi
        fi
    done
    
    log_success "Configuration cleanup complete"
}

# Show usage information
show_usage() {
    cat << EOF
Configuration Manager - Unified Configuration System

USAGE:
    $(basename "$0") COMMAND

COMMANDS:
    generate    Generate all configuration files from master config
    validate    Validate master configuration file
    sync        Sync changes to all configuration files (same as generate)
    clean       Remove all generated configuration files
    help        Show this help message

DESCRIPTION:
    This script manages a unified configuration system that eliminates
    redundant configuration parameters across multiple files. All
    configuration is centralized in config/deployment.conf.

EXAMPLES:
    $(basename "$0") generate    # Generate all config files
    $(basename "$0") validate    # Check master config validity
    $(basename "$0") clean       # Remove generated files

EOF
}

# Main function
main() {
    case "${1:-}" in
        generate|sync)
            generate_all_configs
            ;;
        validate)
            load_master_config
            validate_config
            ;;
        clean)
            clean_configs
            ;;
        help|--help|-h)
            show_usage
            ;;
        "")
            log_error "No command specified"
            show_usage
            exit 1
            ;;
        *)
            log_error "Unknown command: $1"
            show_usage
            exit 1
            ;;
    esac
}

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi